<?php
    $user = $this->users;
?>

<body>
    
    <label for="" class="w-screen border-0 bg-gray-300 text-center font-bold px-3 pt-8 pb-2 text-pink-600 text-4xl">Crear una nova tasca</label>
    
    <form action="storetask" method="POST" class="flex justify-center">
        <section class="flex justify-center items-center bg-gray-300 text-center w-full ">
            <div class="max-w-md w-full bg-white p-6 my-4 space-y-4 shadow-2xl rounded-2xl">

                <label for="inpCrated_at" class=" block text-sm text-left font-bold text-pink-600 text-4xl">Data creació:</label>
                <input 
                    id   = "inpCreated_at"
                    type = "datetime"
                    value= "<?php 
                        $mydate=getdate(date("U"));
                        echo "$mydate[year]-$mydate[mon]-$mydate[mday]"; 
                        ?>" 
                    name = "created_at"
                    class= "block w-full px-3 py-3 
                            border border-solid border-gray-400 rounded transition ease-in-out m-0 
                            text-base font-normal text-gray-700 bg-white-200 bg-clip-padding
                            focus:outline-none focus:bg-pink-100 focus:border-gray-500"
                    autofocus 
                    tabindex="1"
                />            

                <label for="inpDescrip" class=" block text-sm text-left font-bold text-pink-600 text-4xl">Descripció:</label>
                <input 
                    id   = "inpDescrip"
                    type ="text"
                    value="entrar nom tasca..."
                    name ="description"
                    class="block w-full py-3 px-3
                            border border-solid border-slate-500 rounded transition ease-in-out m-0 
                            text-base font-normal text-gray-700 bg-white-200 bg-clip-padding
                            focus:outline-none focus:bg-pink-100 focus:border-gray-500"
                    tabindex="2"
                />
                               
                <label for="cmbUserMaster" class=" block text-sm text-left font-bold text-pink-600 text-4xl"> Usuari creador:</label>
                <select 
                    id   = "cmbUserMaster" 
                    name = "masterUsr_id"
                    class="block w-full py-3 px-3 pr8
                            flex items-center justify-center block appearance-none bg-white-200 
                            border border-solid border-slate-500 rounded text-gray-700 leading-tight 
                            focus:outline-none focus:bg-pink-100 focus:border-gray-500"
                    tabindex="3"
                    >
                    <?php 
                        foreach ($user as $key){
                                echo '<option value="' . $key['id_user'] . '"> ' . $key['name'] . ' </option>  ' ;                          
                        } 
                    ?> 
                </select>

                <label for="cmbUserSlave" class=" block text-sm text-left font-bold text-pink-600 text-4xl"> Usuari executor:</label>
                <select 
                    id   = "cmbUserSlave" 
                    name = "slaveUsr_id"
                    class="flex items-center justify-center block appearance-none w-full bg-white-200 border border-slate-500 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-pink-100 focus:border-gray-500"
                    tabindex="4"
                    >

                    <?php 
                        foreach ($user as $key){
                                echo '<option value="' . $key['id_user'] . '"> ' . $key['name'] . ' </option>  ' ;                          
                        } 
                    ?> 
 
                </select>

                <label for="cmbCurrentStatus" class=" block text-sm text-left font-bold text-pink-600 text-4xl"> Estat:</label>
                <div class="max-w-md w-full bg-white rounded p-0 mb-6 space-y-0">
                    <select 
                        id   ="cmbCurrentStatus"  
                        name ="cmbCurrentStatus"
                        class="block appearance-none w-full bg-white-200 border border-slate-500 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-pink-100 focus:border-gray-500 text-center"
                        tabindex="5"
                        >
                        <option value="To do" class="bg-yellow-200 text-yellow-800" selected>To do</option>
                        <option value="In Progress" class="bg-blue-200 text-blue-800">In Progress</option>
                        <option value="Completed" class="bg-green-200 text-green-800">Completed</option>
                        <option value="In Problems" class="bg-red-200 text-red-800">In Problems</option>
                    </select>                          
                </div>
              
                <div class = "flex items-center justify-evenly pt-4">
                    <button type="submit" id="cancel" name="cancel" class="w-40 mt-8 py-3 bg-gray-300 hover:bg-gray-400 rounded text-sm font-bold text-pink-600 border-pink-600 transition duration-200">
                        <a  href="viewalltask" 
                            class="no-underline hover:no-underline text-pink-600 border-pink-600 transition duration-200 hover:text-pink-600" 
                            tabindex="6"
                        > Cancel·lar </a>
                    </button>                  
                    <button 
                        type="submit" 
                        id ="addtask" 
                        name="addtask" 
                        class="w-40 mt-8 py-3 bg-pink-600 hover:bg-pink-800 rounded text-sm font-bold text-gray-50 transition duration-200"
                        tabindex="7"
                        >
                        Crear
                    </button>
                </div>

            </div>
        </section>                
    </form>
      
</body>

<?php
      
      