<?php
    $task = $this->data;
    $user = $this->users;
?>

<body>

    <label class="w-screen border-0 bg-gray-300 text-center font-bold px-3 pt-8 pb-2 text-pink-600 text-4xl">Editar la tasca</label>

    <form action="updatetask" method="POST" class="flex justify-center ">
            
        <section class="flex justify-center items-center bg-gray-300 text-center w-full ">
            <div class="max-w-md w-full bg-white p-6 my-4 space-y-4 shadow-2xl rounded-2xl">
                <!-- <p class="text-red-500 text-xs italic">Please fill out this field.</p> -->

                <input 
                    id   = "inpId"
                    type = "hidden"                     
                    value= "<?php echo $task['id_task'] ?>"
                    name = "inpId"                    
                />

                <label for="inpCrated_at" class=" block text-sm text-left font-bold text-pink-600 text-4xl">Data creació:</label>
                <input 
                    id   = "inpCreated_at"
                    type = "text"
                    value= "<?php echo $task['created_at'] ?>"                    
                    name = "created_at"
                    class= "block w-full px-3 py-3 
                            border border-solid border-gray-400 rounded transition ease-in-out m-0 
                            text-base font-normal text-gray-700 bg-white-200 bg-clip-padding
                            focus:outline-none focus:bg-pink-100 focus:border-gray-500"                                                
                    autofocus 
                    tabindex="1"
                />

                <label for="inpDescrip" class=" block text-sm text-left font-bold text-pink-600 text-4xl">Descripció:</label>
                <input 
                    id   = "inpDescrip"
                    type ="text"
                    value="<?php echo $task['description'] ?>"                    
                    name ="inpDescrip"
                    class="block w-full py-3 px-3
                            border border-solid border-slate-500 rounded transition ease-in-out m-0 
                            text-base font-normal text-gray-700 bg-white-200 bg-clip-padding
                            focus:outline-none focus:bg-pink-100 focus:border-gray-500"
                    tabindex="2"
                />

                <label for="cmbUserMaster" class="block text-sm text-left font-bold text-pink-600 text-4xl">Usuari creador:</label>
                <select 
                    id   = "cmbUserMaster" 
                    name = "cmbUserMaster" 
                    class="block w-full py-3 px-3 pr8
                            flex items-center justify-center block appearance-none bg-white-200 
                            border border-solid border-slate-500 rounded text-gray-700 leading-tight 
                            focus:outline-none focus:bg-pink-100 focus:border-gray-500"
                    tabindex="3"
                    >                    
                    <?php 
                        foreach ($user as $key){
                            if ($key['id_user'] == $task['masterUsr_id']) {
                                echo '<option value="' . $key['id_user'] . '" selected> ' . $key['name'] . ' </option>  ' ;
                            }else{
                                echo '<option value="' . $key['id_user'] . '"> ' . $key['name'] . ' </option>  ' ;
                            }
                        } 
                    ?> 
                </select>
                
                <label for="cmbUserSlave" class="block text-sm text-left font-bold text-pink-600 text-4xl">Usuari executor:</label>
                <select 
                    id   = "cmbUserSlave" 
                    name = "cmbUserSlave"
                    class="block w-full py-3 px-3 pr8
                            flex items-center justify-center block appearance-none bg-white-200 
                            border border-solid border-slate-500 rounded text-gray-700 leading-tight 
                            focus:outline-none focus:bg-pink-100 focus:border-gray-500"
                    tabindex="4"
                    >
                    <?php 
                        foreach ($user as $key){
                            if ($key['id_user'] == $task['slaveUsr_id']) {
                                echo '<option value="' . $key['id_user'] . '" selected> ' . $key['name'] . ' </option>  ' ;
                            }else{
                                echo '<option value="' . $key['id_user'] . '"> ' . $key['name'] . ' </option>  ' ;
                            }
                        } 
                    ?> 
                </select>

                <label for="cmbCurrentStatus" class="block text-sm text-left font-bold text-pink-600 text-4xl">Status:</label>                
                <div class="max-w-md w-full bg-white rounded p-6 my-1 space-y-2">
                    <select 
                        id   ="cmbCurrentStatus"  
                        name ="cmbCurrentStatus"
                        class="block appearance-none w-full bg-white-200 border border-slate-300 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-pink-100 focus:border-gray-500 text-center"
                        tabindex="5"                        
                        >
                        <option value="To do" 
                            <?php if(!empty($task)) echo ($task['currentStatus'] == 'To do') ? ' selected' : '' ?>
                        >To do</option>

                        <option value="In Progress"
                            <?php if(!empty($task)) echo ($task['currentStatus'] == 'In Progress') ? ' selected' : '' ?>                        
                        >In Progress</option>

                        <option value="Completed"
                            <?php if(!empty($task)) echo ($task['currentStatus'] == 'Completed') ? ' selected' : '' ?>                        
                        >Completed</option>

                        <option value="In Problems"
                            <?php if(!empty($task)) echo ($task['currentStatus'] == 'In Problems') ? ' selected' : '' ?>                        
                        >In Problems</option>
                    </select>                          
                </div>                

                <div class = "flex items-center justify-evenly">                        
                    <button type="submit" 
                            id="cancel" 
                            name="cancel" 
                            class="w-40 py-4 bg-gray-300 hover:bg-gray-400 rounded text-sm font-bold text-pink-600 border-pink-600 transition duration-200" >

                        <a  href="viewalltask" 
                            class="no-underline hover:no-underline focus:border-pink-400 focus:outline-none text-pink-600 border-pink-600 transition duration-200 hover:text-pink-600"
                            tabindex="6"
                        >
                           Cancel·lar
                        </a>
                    </button>
                    <button type="submit" 
                            id="btnSaveTask" 
                            name="btnSaveTask" 
                            class="w-40 py-4 bg-pink-600 hover:bg-pink-800 focus:border-60 focus:outline-pink-200 rounded text-sm font-bold text-gray-50 transition duration-200"
                            tabindex="7"
                            >
                        Modificar
                    </button>
                </div>
            </div>
            
        </section>
 
    </form>
</body>
