<?php
    $task = $this->data;
    $user = $this->users;
?>

<body>

    <label class="w-screen border-0 bg-gray-300 text-center font-bold px-3 py-12 text-pink-600 text-4xl"> EDIT TASK </label>

    <form action="updatetask" method="POST" class="flex justify-center ">
            
        <section class="flex justify-center items-center bg-gray-300 text-center w-full ">
            <div class="max-w-md w-full  bg-white rounded p-6 my-4 space-y-4">
                <!-- <p class="text-red-500 text-xs italic">Please fill out this field.</p> -->

                <input 
                    id   = "inpId"
                    type = "hidden"                     
                    value= "<?php echo $task['id_task'] ?>"
                    name = "inpId"                    
                />

                <label for="inpCrated_at" class=" block text-sm text-left font-bold text-pink-600 text-4xl">Data creació:</label>
                <input 
                    id   = "inpCreated_at"
                    type = "text"
                    value= "<?php echo $task['created_at'] ?>"                    
                    name = "created_at"
                    class= "form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                    placeholder="Pick a date"
                />

                <label for="inpDescrip" class=" block text-sm text-left font-bold text-pink-600 text-4xl">Descripció:</label>
                <input 
                    id   = "inpDescrip"
                    type ="text"
                    value="<?php echo $task['description'] ?>"                    
                    name ="inpDescrip"
                    class="justify-center shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                />

                <label for="cmbUserMaster" class="block text-sm text-left font-bold text-pink-600 text-4xl">Usuari creador:</label>
                <select 
                    id   = "cmbUserMaster" 
                    name = "cmbUserMaster" 
                    class="flex items-center justify-center block appearance-none w-full bg-white border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500">

                    <?php 
                        foreach ($user as $key){
                            if ($key['id_user'] == $task['masterUsr_id']) {
                                echo '<option value="' . $key['id_user'] . '" selected> ' . $key['name'] . ' </option>  ' ;
                            }else{
                                echo '<option value="' . $key['id_user'] . '"> ' . $key['name'] . ' </option>  ' ;
                            }
                        } 
                    ?> 

                </select>
                
                <label for="cmbUserSlave" class="block text-sm text-left font-bold text-pink-600 text-4xl">Usuari executor:</label>
                <select 
                    id   = "cmbUserSlave" 
                    name = "cmbUserSlave"
                    class="flex items-center justify-center block appearance-none w-full bg-white border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500">

                    <?php 
                        foreach ($user as $key){
                            if ($key['id_user'] == $task['slaveUsr_id']) {
                                echo '<option value="' . $key['id_user'] . '" selected> ' . $key['name'] . ' </option>  ' ;
                            }else{
                                echo '<option value="' . $key['id_user'] . '"> ' . $key['name'] . ' </option>  ' ;
                            }
                        } 
                    ?> 
 
                </select>

                <label for="cmbCurrentStatus" class="block text-sm text-left font-bold text-pink-600 text-4xl">Status:</label>                
                <div class="max-w-md w-full  bg-white rounded p-6 my-1 space-y-2">
                    <select 
                        id   ="cmbCurrentStatus"  
                        name ="cmbCurrentStatus"
                        class="block appearance-none w-full bg-white-200 border border-slate-300 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500 text-center">
                        <option value="Initiated" 
                            <?php if(!empty($task)) echo ($task['currentStatus'] == 'Initiated') ? ' selected' : '' ?>
                        >Initiated</option>

                        <option value="In Progress"
                            <?php if(!empty($task)) echo ($task['currentStatus'] == 'In Progress') ? ' selected' : '' ?>                        
                        >In Progress</option>

                        <option value="Completed"
                            <?php if(!empty($task)) echo ($task['currentStatus'] == 'Completed') ? ' selected' : '' ?>                        
                        >Completed</option>

                        <option value="Deleted"
                            <?php if(!empty($task)) echo ($task['currentStatus'] == 'Deleted') ? ' selected' : '' ?>                        
                        >Deleted</option>
                    </select>                          
                </div>                

                <div class = "flex items-center justify-evenly">                        
                    <button type="submit" 
                            id="cancel" 
                            name="cancel" 
                            class="w-40 py-4 bg-gray-300 hover:bg-gray-400 rounded text-sm font-bold text-pink-600 border-pink-600 transition duration-200" >

                        <a href="viewalltask" class="underline hover:no-underline no-underline text-pink-600 border-pink-600 transition duration-200 hover:text-pink-600">
                           < Cancel·lar i tornar
                        </a>
                    </button>
                    <button type="submit" 
                            id="btnSaveTask" 
                            name="btnSaveTask" 
                            class="w-40 py-4 bg-pink-600 hover:bg-pink-800 rounded text-sm font-bold text-gray-50 transition duration-200">
                        Modificar tasca
                    </button>
                </div>
            </div>
            
        </section>
 
    </form>
</body>
