<?php 
    // include ROOT_PATH.'/web/includes/header.php';
    $controllerTasks = new TaskController;
    $tasks = $controllerTasks->viewallAction();
    $controllerUsers = new UserController;
    $users = $controllerUsers->getAllUsersAction();
?>

<body>
    <label for="" class="w-screen border-0 text-center font-bold px-3 py-6 text-pink-600 text-4xl"> Llistat de tasques </label>
    <form action ="" method="POST" class="flex justify-center items-center border-0">        
        
        <div class="pt-2 bg-gray-300 container flex justify-center mx-auto border-0">
            <div class="flex flex-col">
            <section class="pb-2 mb-4 px-8 flex items-center justify-between">
                    <button type="submit" id="btnLogout" name="btnLogout" class="w-40 py-2 mb-2 bg-pink-600 hover:bg-pink-800 rounded text-sm font-bold text-gray-50 border-pink-600 transition duration-200">
                        <a href="logout" class=" underline hover:no-underline no-underline border-pink-600 transition duration-200 hover:text-gray-50" > Logout</a>
                    </button>                       
                    <button type= "submit" id = "addtask" name = "addtask" class="w-40 py-2 mb-2 bg-pink-600 hover:bg-pink-800 rounded text-sm font-bold text-gray-50 transition duration-200" >
                        <a href="addtask" class =" underline hover:no-underline no-underline text-white" >Crear nova</a>
                    </button>
                </section>
                <div class="w-full">                    
                    <div class="border border-gray-200 shadow-2xl rounded-2xl">
                        <table class="divide-y divide-gray-300 ">
                            <thead class="bg-gray-50">
                                <tr>
                                    <!-- <th class="px-6 py-2 text-xs text-gray-500">
                                        ID
                                    </th> -->
                                    <th class="px-6 py-3 text-sm text-pink-800 bg-pink-200">
                                        Creaci&oacute;
                                    </th>         
                                    <th class="px-6 py-2 text-sm text-pink-800 bg-pink-200">
                                        Status
                                    </th>                                                               
                                    <th  class="px-6 py-3 text-sm text-pink-800 bg-pink-200">
                                        Descripci&oacute;
                                    </th>
                                    <th class="px-6 py-3 text-sm text-pink-800 bg-pink-200">
                                        Creador
                                    </th>
                                    <th class="px-6 py-3 text-sm text-pink-800 bg-pink-200">
                                        Executor
                                    </th>                                    
                                    <th class="px-6 py-3 text-sm text-pink-800 bg-pink-200">
                                        Editar
                                    </th>
                                    <th class="px-6 py-3 text-sm text-pink-800 bg-pink-200">
                                        Eliminar
                                    </th>
                                </tr>
                            </thead>
                            <tbody class="bg-white divide-y divide-pink-300">

                                <?php foreach ($tasks as $key => $task) :?>

                                <tr class="whitespace-nowrap">
                                    <!-- <td id = 'id_task' class="px-6 py-4 text-sm text-gray-500">
                                        <?php echo $task['id_task']?>
                                    </td> -->
                                    <td id='created_at' class="px-6 py-4 text-sm text-gray-500">
                                        <?php echo $task['created_at']?>
                                    </td>
                                    <td id='currentStatus' class="px-6 py-4">
                                        <div class="text-sm text-gray-900">
                                            <?php 
                                                switch ($task['currentStatus']){
                                                    case 'Completed': echo '<span class="text-green-600 font-bold">'.$task['currentStatus'].'</span>';break;
                                                    case 'To do':     echo '<span class="text-yellow-600 font-bold">'.$task['currentStatus'].'</span>';break;
                                                    case 'In Progress': echo '<span class="text-blue-600 font-bold">'.$task['currentStatus'].'</span>';break;
                                                    case 'In Problems': echo '<span class="text-red-600 font-bold">'.$task['currentStatus'].'</span>';break;
                                                }
                                            ?>
                                        </div>
                                    </td>                                    
                                    <td id='description' class="px-6 py-4">
                                        <div class="text-sm text-gray-900">
                                        <?php echo $task['description']?>
                                        </div>
                                    </td>                                    
                                    <td id='masterUsr_id' class="px-6 py-4 text-sm text-gray-500">
                                        <!-- <?php echo $task['masterUsr_id']?> -->
                                        <?php foreach ($users as $key => $user) :
                                                if ($user['id_user'] == $task['masterUsr_id'] ) {
                                                    echo $user['name'];
                                                }
                                            endforeach; 
                                        ?>
                                    </td>
                                    <td id='slaveUsr_id ' class="px-6 py-4 text-sm text-gray-500">
                                        <!-- <?php echo $task['slaveUsr_id']?> -->
                                        <?php foreach ($users as $key => $user) :
                                            if ($user['id_user'] == $task['slaveUsr_id'] ) {
                                                echo $user['name'];
                                            }
                                        endforeach;                                         
                                        ?>
                                    </td>                                    
                                    <td class="px-6 py-4">
                                        <a href="edittask?id_task=<?php echo $task['id_task']?>">
                                            <svg  class="w-6 h-6 text-blue-400" fill="none"
                                                viewBox="0 0 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                    d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                                            </svg>
                                        </a>
                                    </td>
                                    <td class="px-6 py-4">
                                        <a href="deltask?id_task=<?php echo $task['id_task']?>">
                                            <svg  class="w-6 h-6 text-red-400" fill="none"
                                                viewBox="0 0 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                    d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                            </svg>
                                        </a>
                                    </td>
                                </tr>

                                <?php endforeach; ?>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>    
    </form>
</body>
